#!/bin/sh

# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/common/generate-blob-scripts.sh - DO NOT EDIT

DEVICE=stuttgart_row
MANUFACTURER=lenovo

mkdir -p ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
mkdir -p ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/etc/wifi

adb root
sleep 3

adb pull /system/bin/glgps ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/bin/glgps
adb pull /system/bin/hostapd ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/bin/hostapd
adb pull /system/bin/stmd ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/bin/stmd

adb pull /system/etc/firmware/fw_bcmdhd_p2p.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/etc/firmware/fw_bcmdhd_p2p.bin
adb pull /system/etc/firmware/fw_bcmdhd_apsta.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/etc/firmware/fw_bcmdhd_apsta.bin
adb pull /system/etc/firmware/fw_bcmdhd.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/etc/firmware/fw_bcmdhd.bin
adb pull /system/etc/wifi/bcmdhd.cal ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/etc/wifi/bcmdhd.cal
adb pull /system/etc/rril/stmd.conf ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/etc/rril/stmd.conf
adb pull /system/etc/rril/repository.txt ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/etc/rril/repository.txt

adb pull /system/lib/egl/libEGL_mali.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/egl/libEGL_mali.so
adb pull /system/lib/egl/libGLES_android.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/egl/libGLES_android.so
adb pull /system/lib/egl/libGLESv1_CM_mali.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/egl/libGLESv1_CM_mali.so
adb pull /system/lib/egl/libGLESv2_mali.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/egl/libGLESv2_mali.so

adb pull /system/lib/hw/lights.stuttgart_row.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/hw/lights.stuttgart_row.so
adb pull /system/lib/hw/gps.exynos4.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/hw/gps.exynos4.so
adb pull /system/lib/hw/gralloc.stuttgart_row.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/hw/gralloc.stuttgart_row.so
adb pull /system/lib/hw/sensors.exynos4.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/hw/sensors.exynos4.so
adb pull /system/lib/hw/hwcomposer.exynos4.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/hw/hwcomposer.exynos4.so
adb pull /system/lib/hw/camera.stuttgart_row.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/hw/camera.stuttgart_row.so

adb pull /system/lib/libril.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/libril.so
adb pull /system/lib/libion.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/libion.so
adb pull /system/lib/libMali.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/libMali.so
adb pull /system/lib/libUMP.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/libUMP.so
adb pull /system/lib/libfimg.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/libfimg.so
adb pull /system/lib/libhwconverter.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/libhwconverter.so
adb pull /system/lib/libhwjpeg.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/libhwjpeg.so
adb pull /system/lib/libfimc.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/libfimc.so
adb pull /system/lib/libswscaler.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/libswscaler.so
adb pull /system/lib/librapid-ril-util.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/librapid-ril-util.so
adb pull /system/lib/librapid-ril-core.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/librapid-ril-core.so
adb pull /system/lib/libSEC_OMX_Core.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/libSEC_OMX_Core.so
adb pull /system/lib/libSEC_OMX_Resourcemanager.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/libSEC_OMX_Resourcemanager.so
adb pull /system/lib/libLeImageLightness.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/libLeImageLightness.so
adb pull /system/lib/libcamera_client.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/libcamera_client.so
adb pull /system/lib/libstagefrighthw.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/libstagefrighthw.so
adb pull /system/lib/modules/bcmdhd.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/modules/bcmdhd.ko
adb pull /system/lib/omx/libOMX.SEC.AVC.Decoder.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/omx/libOMX.SEC.AVC.Decoder.so
adb pull /system/lib/omx/libOMX.SEC.AVC.Encoder.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/omx/libOMX.SEC.AVC.Encoder.so
adb pull /system/lib/omx/libOMX.SEC.M2V.Decoder.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/omx/libOMX.SEC.M2V.Decoder.so
adb pull /system/lib/omx/libOMX.SEC.M4V.Decoder.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/omx/libOMX.SEC.M4V.Decoder.so
adb pull /system/lib/omx/libOMX.SEC.M4V.Encoder.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/omx/libOMX.SEC.M4V.Encoder.so
adb pull /system/lib/omx/libOMX.SEC.WMV.Decoder.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/lib/omx/libOMX.SEC.WMV.Decoder.so

adb pull /system/usr/idc/atmel-touchscreen.idc ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/usr/idc/atmel-touchscreen.idc
adb pull /system/usr/idc/qwerty.idc ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/usr/idc/qwerty.idc
adb pull /system/usr/idc/qwerty2.idc ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/usr/idc/qwerty2.idc
adb pull /system/usr/idc/ft5x0x_ts.idc ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/usr/idc/ft5x0x_ts.idc
adb pull /system/usr/idc/pixcir-i2c-ts.idc ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/usr/idc/pixcir-i2c-ts.idc

adb pull /system/usr/keychars/Generic.kcm ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/usr/keychars/Generic.kcm
adb pull /system/usr/keychars/qwerty.kcm ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/usr/keychars/qwerty.kcm
adb pull /system/usr/keychars/qwerty2.kcm ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/usr/keychars/qwerty2.kcm
adb pull /system/usr/keychars/Virtual.kcm ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/usr/keychars/Virtual.kcm

adb pull /system/usr/keylayout/AVRCP.kl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/usr/keylayout/AVRCP.kl
adb pull /system/usr/keylayout/Generic.kl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/usr/keylayout/Generic.kl
adb pull /system/usr/keylayout/atmel-key.kl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/usr/keylayout/atmel-key.kl
adb pull /system/usr/keylayout/headset.kl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/usr/keylayout/headset.kl
adb pull /system/usr/keylayout/qwerty.kl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/usr/keylayout/qwerty.kl
adb pull /system/usr/keylayout/Vendor_045e_Product_028e.kl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/usr/keylayout/Vendor_045e_Product_028e.kl
adb pull /system/usr/keylayout/Vendor_046d_Product_c216.kl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/usr/keylayout/Vendor_046d_Product_c216.kl
adb pull /system/usr/keylayout/Vendor_046d_Product_c294.kl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/usr/keylayout/Vendor_046d_Product_c294.kl
adb pull /system/usr/keylayout/Vendor_046d_Product_c299.kl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/usr/keylayout/Vendor_046d_Product_c299.kl
adb pull /system/usr/keylayout/Vendor_046d_Product_c532.kl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/usr/keylayout/Vendor_046d_Product_c532.kl
adb pull /system/usr/keylayout/Vendor_05ac_Product_0239.kl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/usr/keylayout/Vendor_05ac_Product_0239.kl
adb pull /system/usr/keylayout/Vendor_22b8_Product_093d.kl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/usr/keylayout/Vendor_22b8_Product_093d.kl
adb pull /system/usr/keylayout/Vendor_054c_Product_0268.kl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/system/usr/keylayout/Vendor_054c_Product_0268.kl

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__MANUFACTURER__/$MANUFACTURER/g > ../../../vendor/$MANUFACTURER/$DEVICE/$DEVICE-vendor-blobs.mk
# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__MANUFACTURER__/__DEVICE__/extract-files.sh - DO NOT EDIT

LOCAL_PATH := vendor/__MANUFACTURER__/__DEVICE__

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \\
    \$(LOCAL_PATH)/proprietary/system/lib/libril.so:obj/lib/libril.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/libion.so:obj/lib/libion.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/libUMP.so:obj/lib/libUMP.so

PRODUCT_COPY_FILES += \\
    \$(LOCAL_PATH)/proprietary/system/bin/glgps:system/bin/glgps \\
    \$(LOCAL_PATH)/proprietary/system/bin/hostapd:system/bin/hostapd \\
    \$(LOCAL_PATH)/proprietary/system/bin/stmd:system/bin/stmd

PRODUCT_COPY_FILES += \\
    \$(LOCAL_PATH)/proprietary/system/etc/firmware/fw_bcmdhd_p2p.bin:system/etc/firmware/fw_bcmdhd_p2p.bin \\
    \$(LOCAL_PATH)/proprietary/system/etc/firmware/fw_bcmdhd_apsta.bin:system/etc/firmware/fw_bcmdhd_apsta.bin \\
    \$(LOCAL_PATH)/proprietary/system/etc/firmware/fw_bcmdhd.bin:system/etc/firmware/fw_bcmdhd.bin

PRODUCT_COPY_FILES += \\
    \$(LOCAL_PATH)/proprietary/system/etc/wifi/bcmdhd.cal:system/etc/wifi/bcmdhd.cal

PRODUCT_COPY_FILES += \\
    \$(LOCAL_PATH)/proprietary/system/lib/egl/libEGL_mali.so:system/lib/egl/libEGL_mali.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/egl/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/egl/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so

PRODUCT_COPY_FILES += \\
    \$(LOCAL_PATH)/proprietary/system/lib/hw/lights.stuttgart_row.so:system/lib/hw/lights.stuttgart_row.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/hw/gps.exynos4.so:system/lib/hw/gps.exynos4.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/hw/gralloc.stuttgart_row.so:system/lib/hw/gralloc.stuttgart_row.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/hw/sensors.exynos4.so:system/lib/hw/sensors.exynos4.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/hw/hwcomposer.exynos4.so:system/lib/hw/hwcomposer.exynos4.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/hw/camera.stuttgart_row.so:system/lib/hw/camera.stuttgart_row.so

PRODUCT_COPY_FILES += \\
    \$(LOCAL_PATH)/proprietary/system/lib/libril.so:system/lib/libril.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/libion.so:system/lib/libion.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/libMali.so:system/lib/libMali.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/libUMP.so:system/lib/libUMP.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/libfimg.so:system/lib/libfimg.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/libhwconverter.so:system/lib/libhwconverter.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/libhwjpeg.so:system/lib/libhwjpeg.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/libfimc.so:system/lib/libfimc.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/libswscaler.so:system/lib/libswscaler.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/librapid-ril-util.so:system/lib/librapid-ril-util.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/librapid-ril-core.so:system/lib/librapid-ril-core.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/libSEC_OMX_Core.so:system/lib/libSEC_OMX_Core.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/libSEC_OMX_Resourcemanager.so:system/lib/libSEC_OMX_Resourcemanager.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/libLeImageLightness.so:system/lib/libLeImageLightness.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/libcamera_client.so:system/lib/libcamera_client.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/modules/bcmdhd.ko:system/lib/modules/bcmdhd.ko \\
    \$(LOCAL_PATH)/proprietary/system/lib/omx/libOMX.SEC.AVC.Decoder.so:system/lib/omx/libOMX.SEC.AVC.Decoder.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/omx/libOMX.SEC.AVC.Encoder.so:system/lib/omx/libOMX.SEC.AVC.Encoder.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/omx/libOMX.SEC.M2V.Decoder.so:system/lib/omx/libOMX.SEC.M2V.Decoder.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/omx/libOMX.SEC.M4V.Decoder.so:system/lib/omx/libOMX.SEC.M4V.Decoder.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/omx/libOMX.SEC.M4V.Encoder.so:system/lib/omx/libOMX.SEC.M4V.Encoder.so \\
    \$(LOCAL_PATH)/proprietary/system/lib/omx/libOMX.SEC.WMV.Decoder.so:system/lib/omx/libOMX.SEC.WMV.Decoder.so

PRODUCT_COPY_FILES += \\
    \$(LOCAL_PATH)/proprietary/system/usr/idc/atmel-touchscreen.idc:system/usr/idc/atmel-touchscreen.idc \\
    \$(LOCAL_PATH)/proprietary/system/usr/idc/qwerty.idc:system/usr/idc/qwerty.idc \\
    \$(LOCAL_PATH)/proprietary/system/usr/idc/qwerty2.idc:system/usr/idc/qwerty2.idc \\
    \$(LOCAL_PATH)/proprietary/system/usr/idc/ft5x0x_ts.idc:system/usr/idc/ft5x0x_ts.idc \\
    \$(LOCAL_PATH)/proprietary/system/usr/idc/pixcir-i2c-ts.idc:system/usr/idc/pixcir-i2c-ts.idc

PRODUCT_COPY_FILES += \\
    \$(LOCAL_PATH)/proprietary/system/usr/keychars/Generic.kcm:system/usr/keychars/Generic.kcm \\
    \$(LOCAL_PATH)/proprietary/system/usr/keychars/qwerty.kcm:system/usr/keychars/qwerty.kcm \\
    \$(LOCAL_PATH)/proprietary/system/usr/keychars/qwerty2.kcm:system/usr/keychars/qwerty2.kcm \\
    \$(LOCAL_PATH)/proprietary/system/usr/keychars/Virtual.kcm:system/usr/keychars/Virtual.kcm

PRODUCT_COPY_FILES += \\
    \$(LOCAL_PATH)/proprietary/system/usr/keylayout/AVRCP.kl:system/usr/keylayout/AVRCP.kl \\
    \$(LOCAL_PATH)/proprietary/system/usr/keylayout/Generic.kl:system/usr/keylayout/Generic.kl \\
    \$(LOCAL_PATH)/proprietary/system/usr/keylayout/atmel-key.kl:system/usr/keylayout/atmel-key.kl \\
    \$(LOCAL_PATH)/proprietary/system/usr/keylayout/headset.kl:system/usr/keylayout/headset.kl \\
    \$(LOCAL_PATH)/proprietary/system/usr/keylayout/qwerty.kl:system/usr/keylayout/qwerty.kl \\
    \$(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_045e_Product_028e.kl:system/usr/keylayout/Vendor_045e_Product_028e.kl \\
    \$(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_046d_Product_c216.kl:system/usr/keylayout/Vendor_046d_Product_c216.kl \\
    \$(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_046d_Product_c294.kl:system/usr/keylayout/Vendor_046d_Product_c294.kl \\
    \$(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_046d_Product_c299.kl:system/usr/keylayout/Vendor_046d_Product_c299.kl \\
    \$(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_046d_Product_c532.kl:system/usr/keylayout/Vendor_046d_Product_c532.kl \\
    \$(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_05ac_Product_0239.kl:system/usr/keylayout/Vendor_05ac_Product_0239.kl \\
    \$(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_22b8_Product_093d.kl:system/usr/keylayout/Vendor_22b8_Product_093d.kl \\
    \$(LOCAL_PATH)/proprietary/system/usr/keylayout/Vendor_054c_Product_0268.kl:system/usr/keylayout/Vendor_054c_Product_0268.kl

EOF

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__MANUFACTURER__/$MANUFACTURER/g > ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/Android.mk
# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__MANUFACTURER__/__DEVICE__/extract-files.sh - DO NOT EDIT

ifeq (\$(TARGET_DEVICE),i9300)
LOCAL_PATH:=\$(call my-dir)
endif

EOF

exec ./setup-makefiles.sh
